export const WORKSHOP_STARTER_CATEGORIES = [
  { name: 'Manutencao Preventiva', description: 'Trocas, revisoes e manutencoes programadas' },
  { name: 'Mecanica Geral', description: 'Diagnostico e reparos mecanicos' },
  { name: 'Eletrica', description: 'Sistemas eletricos, partida, carga e sensores' },
  { name: 'Freios e Suspensao', description: 'Pastilhas, discos, amortecedores e componentes' },
  { name: 'Funilaria e Pintura', description: 'Lataria, acabamento e pintura' },
]

export const WORKSHOP_STARTER_PRODUCTS = [
  {
    name: 'Oleo motor 5W30',
    description: 'Item base para revisoes e trocas de oleo',
    sku: 'STARTER-OLEO-5W30',
    costPrice: 0,
    price: 0,
    stock: 0,
    minStock: 4,
    location: 'Estoque principal',
    supplier: 'Fornecedor a definir',
  },
  {
    name: 'Filtro de oleo',
    description: 'Filtro de reposicao para manutencao preventiva',
    sku: 'STARTER-FILTRO-OLEO',
    costPrice: 0,
    price: 0,
    stock: 0,
    minStock: 4,
    location: 'Estoque principal',
    supplier: 'Fornecedor a definir',
  },
  {
    name: 'Filtro de ar',
    description: 'Filtro de ar para revisoes recorrentes',
    sku: 'STARTER-FILTRO-AR',
    costPrice: 0,
    price: 0,
    stock: 0,
    minStock: 3,
    location: 'Estoque principal',
    supplier: 'Fornecedor a definir',
  },
  {
    name: 'Pastilha de freio',
    description: 'Item generico para controle inicial de freios',
    sku: 'STARTER-PASTILHA-FREIO',
    costPrice: 0,
    price: 0,
    stock: 0,
    minStock: 2,
    location: 'Estoque principal',
    supplier: 'Fornecedor a definir',
  },
]
